server:
  port: 3003
spring:
  application:
    name: loger
  datasource:
    url: jdbc:mysql://localhost:3306/my?serverTimezone=UTC
    username: root
    password: a128263
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2998/eureka/
