spring:
  application:
    name: edge-node
  datasource:
    url: jdbc:mysql://localhost:3306/my?serverTimezone=UTC
    username: root
    password: a128263
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
server:
  port: 3001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2998/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 开放所有端点health，info，metrics，通过actuator/+端点名就可以获取相应的信息。默认打开health和info
  endpoint:
    health:
      show-details: always  #未开启actuator/health时，我们获取到的信息是{"status":"UP"}，status的值还有可能是 DOWN。开启后打印详细信息


serviceport:
  portmap:
    eureka: 10000
    zuul: 10001