server:
  port: 3001
spring:
  application:
    name: edge-node
  datasource:
    url: jdbc:mysql://localhost:3306/my?serverTimezone=UTC
    username: root
    password: a128263
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2998/eureka/




serviceport:
  portmap:
    eureka: 10000
    zuul: 10001